name: Hots
favicon: null
layout_spectrum: 0.99276
typography_spectrum: 0.3525260975584388
title: Nazeebo Guide Heroes of the Storm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76336257-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.11655666260048747
  lightness: 0.4327543794643134
  saturation: 0.32087882491759956
  rhythmicContrast: 0.5327268503606319
purpose: []
